name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # options
          user: DevxPi
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kuala_Lumpur
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: public
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: star
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_stars: yes
          plugin_stars_limit: 3
